"""The Sponsors action (rulebook p.17).

Level I: play exactly 1 sponsor whose level is at most the action strength, or advance the Break by the strength and take that much
money. Level II: play several sponsors whose levels add up to at most strength + 1, from the hand or from the display within the
reputation range (paying the number of the display folder extra), or take the break option with twice the money. Sponsors that need
the level II icon (requirement `sponsorsII`) can only be played with the upgraded action. Sponsors cost no money.

Requirements come from the card data (`requirements`: an icon name per required icon, repeated for a count). The data does not say how
much 'appeal' / 'reputation' a card needs, (a kiosk requirement means owning a kiosk): `data/sponsor_thresholds.json` is a form for the verified values
(see scripts/infer_sponsor_thresholds.py); unverified requirements are not enforced.
"""
import json
from collections import Counter
from functools import lru_cache
from pathlib import Path

from ark_nova import data
from ark_nova.engine import card_programs, cards_action, effects
from ark_nova.engine.icons import icon_counts
from ark_nova.engine.state import GameState

_ICON_OF_REQUIREMENT = {"science": "Science", "primate": "Primate", "reptile": "Reptile", "bird": "Bird", "predator": "Predator",
                        "herbivore": "Herbivore", "seaAnimal": "SeaAnimal", "americas": "Americas", "africa": "Africa",
                        "europe": "Europe", "asia": "Asia", "australia": "Australia", "bear": "Bear", "pet": "Pet",
                        "Partner Zoo": "Partner-Zoo"}
_THRESHOLDS = Path(data.__file__).with_name("sponsor_thresholds.json")
_EFFECTS = Path(data.__file__).with_name("sponsor_play_effects.json")


@lru_cache(maxsize=None)
def play_effects() -> dict:
    """What each sponsor gives when played (generated by scripts/infer_sponsor_effects.py from the logs)."""
    return json.loads(_EFFECTS.read_text()) if _EFFECTS.exists() else {}


@lru_cache(maxsize=None)
def thresholds() -> dict:
    return json.loads(_THRESHOLDS.read_text()) if _THRESHOLDS.exists() else {}


def level_of(card_key: str) -> int:
    return int(data.cards_by_key()[card_key]["strength"])


def level_for(state, seat: int, card_key: str) -> int:
    """The strength of a sponsor card as this player plays it (maps 8 / 8a: every H covered makes it 1 less)."""
    from ark_nova.engine import map_rules
    return max(0, level_of(card_key) - (1 if map_rules.hollywood_complete(state.players[seat]) else 0))


def budget(action_level: int, strength: int) -> int:
    """Total sponsor levels playable with this action: the strength (one card) at level I, strength + 1 (several) at level II."""
    return strength + (1 if action_level >= 2 else 0)


def own_gain(card_key: str) -> dict:
    """The sponsor's own gain beyond its printed appeal / reputation / conservation (only for cards whose effect is a fixed gain)."""
    if card_key in card_programs.PRINTED_ONLY:
        return {}
    return dict(play_effects().get(card_key, {}).get("gain", {}))


def has_unimplemented_effect(card_key: str) -> bool:
    """Sponsors are implemented when the engine has a program for them (`card_programs`) or the logs show a fixed gain; the others need
    per-card code (formulas over the zoo, choices, ...)."""
    if card_key in card_programs.UNSUPPORTED_PLAY:
        return True
    return not (effects.has_program(card_key) or play_effects().get(card_key, {}).get("kind") == "fixed")


def requirements_met(state: GameState, seat: int, card_key: str, action_level: int) -> bool:
    p = state.players[seat]
    need = Counter(data.cards_by_key()[card_key].get("requirements", []) + card_programs.EXTRA_REQUIREMENTS.get(card_key, []))
    icons = icon_counts(state, seat)
    for req, n in need.items():
        if req == "sponsorsII":
            if action_level < 2:
                return False
        elif req in ("appeal", "reputation"):
            t = thresholds().get(card_key, {}).get(req, {})
            if t.get("verified") and t.get("value") is not None:
                have = p.appeal if req == "appeal" else p.reputation
                if (have > t["value"]) if t.get("op") == "max" else (have < t["value"]):     # "max": Native sponsors need appeal <= 25
                    return False
        elif req in _ICON_OF_REQUIREMENT:
            if icons[_ICON_OF_REQUIREMENT[req]] < n:
                return False
        elif req == "kiosk":
            if not any(b.type == "kiosk" for b in p.buildings):
                return False
    return True


def playable(state: GameState, seat: int, action_level: int, left: int, money: int) -> list[tuple[str, bool]]:
    """(card key, from_display) that can be played now with `left` levels of budget and `money`."""
    p = state.players[seat]
    out = []
    cards = data.cards_by_key()
    for k in sorted(set(p.hand)):
        if k.startswith("S") and level_for(state, seat, k) <= left and requirements_met(state, seat, k, action_level) and effects.can_play(state, seat, k):
            out.append((k, False))
    if action_level >= 2:
        reach = state.display[:cards_action.reputation_range(p.reputation)]
        for folder, k in enumerate(reach, start=1):
            if k and k.startswith("S") and cards[k]["card_type"] == "sponsor" and level_for(state, seat, k) <= left and folder <= money \
                    and requirements_met(state, seat, k, action_level) and effects.can_play(state, seat, k):
                out.append((k, True))
    return out
