"""Analyse log_examples/*.json and write docs/log_events.md (generated: event catalogue, state catalogue, deck-exit stats).

Run: python scripts/analyze_logs.py            (about a minute for ~100 logs)
The hand-written findings live in docs/log_format.md; this file is the raw, regenerated evidence behind them.
"""
import collections
import glob
import json
import os
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "log_events.md"
NOISE = {"gameStateChange", "gameStateMultipleActiveUpdate", "updateReflexionTime", "midmessage", "wakeupPlayers"}

# Classification of `pDrawCards` by the `log` template (see docs/log_format.md, "Deck exits")
DECK_TOP = ("from the deck", "for hunter effect", "for perception effect", "for scuba dive effect", "for sprint effect")
DECK_SEARCH = ("gaining a new university", "with <${type}>", "for monkey gang", "Map 8 effect", "Waza Special")
NOT_DECK = ("scavenging", "Horse Whisperer", "Pilfering", "with Assertion", "with Dominance")


def classify_draw(log: str, scoring: bool) -> str:
    if scoring:
        return "scoring"
    if any(s in log for s in NOT_DECK):
        return "not_deck"
    if any(s in log for s in DECK_SEARCH):
        return "search"
    if any(s in log for s in DECK_TOP):
        return "top"
    return "unknown"


def main() -> None:
    ev = collections.defaultdict(lambda: {"n": 0, "files": set(), "logs": collections.Counter(), "keys": collections.Counter()})
    states = collections.defaultdict(lambda: {"n": 0, "files": set(), "keys": collections.Counter(), "next": collections.Counter()})
    draw_classes = collections.Counter()
    unknown_logs = collections.Counter()
    per_game = []
    files = sorted(glob.glob(str(ROOT / "log_examples" / "*.json")))
    for f in files:
        name = os.path.basename(f)
        d = json.load(open(f, encoding="utf8"))["data"]
        flat = [(p, e) for p in d["logs"] for e in p["data"]]
        seen_ids = {}
        dup = 0
        exits = 0
        for i, (p, e) in enumerate(flat):
            t, a = e["type"], e["args"]
            r = ev[t]
            r["n"] += 1
            r["files"].add(name)
            if e.get("log"):
                r["logs"][re.sub(r"\s+", " ", e["log"])[:90]] += 1
            if isinstance(a, dict):
                for k in a:
                    r["keys"][k] += 1
            if t == "gameStateChange" and isinstance(a, dict):
                sid = a.get("id", a.get("name"))
                s = states[sid]
                s["n"] += 1
                s["files"].add(name)
                aa = a.get("args")
                if isinstance(aa, dict):
                    for k in aa:
                        s["keys"][k] += 1
                for _, x in flat[i + 1:i + 25]:
                    if x["type"] not in NOISE | {"simpleNote", "simpleNode", "newUndoableStep"}:
                        s["next"][x["type"]] += 1
                        break
            if not isinstance(a, dict):
                continue
            ids = []
            if t == "pDrawCards":
                cls = classify_draw(e.get("log", ""), bool(a.get("scoringCard")))
                draw_classes[cls] += 1
                if cls == "unknown":
                    unknown_logs[e.get("log", "")] += 1
                if cls in ("top", "search"):
                    ids = [c["id"] for c in a.get("cards", [])]
            elif t == "fillPool":
                ids = [c["id"] for c in a.get("cards", [])]
            for cid in ids:
                exits += 1
                if cid in seen_ids:
                    dup += 1
                seen_ids[cid] = True
        per_game.append((name, exits, dup))

    L = ["# Log events (generated by scripts/analyze_logs.py)", "",
         f"{len(files)} logs in `log_examples/`. Regenerate after adding logs. Hand-written interpretation: `docs/log_format.md`.", ""]
    L += ["## Event types", "", "| type | count | files | log templates (top) | args keys (share of events) |", "|---|---|---|---|---|"]
    for t, r in sorted(ev.items(), key=lambda kv: -kv[1]["n"]):
        logs = "<br>".join(f"`{k}` ({n})" for k, n in r["logs"].most_common(3))
        keys = ", ".join(f"{k} {100 * n // r['n']}%" for k, n in r["keys"].most_common(9))
        L.append(f"| {t} | {r['n']} | {len(r['files'])} | {logs} | {keys} |")
    L += ["", "## gameStateChange state ids", "",
          "`args.id` (BGA state id). Names are not in the log; meaning is inferred from arg keys and the event that follows.", "",
          "| state id | count | files | args.args keys | next event |", "|---|---|---|---|---|"]
    for sid, s in sorted(states.items(), key=lambda kv: -kv[1]["n"]):
        keys = ", ".join(f"{k}" for k, _ in s["keys"].most_common(8))
        nxt = ", ".join(f"{k} {n}" for k, n in s["next"].most_common(3))
        L.append(f"| {sid} | {s['n']} | {len(s['files'])} | {keys} | {nxt} |")
    L += ["", "## pDrawCards classification (by log template)", "", f"{dict(draw_classes)}", ""]
    if unknown_logs:
        L += ["Unclassified templates:", ""] + [f"- `{k}` ({n})" for k, n in unknown_logs.most_common()]
    bad = [(n, x, dd) for n, x, dd in per_game if dd]
    L += ["", "## Deck-exit duplicates", "",
          "Deck exits = `pDrawCards` classified top/search + `fillPool` new cards. A card leaving the deck twice would mean an "
          "unobserved reshuffle; expected 0.", "", f"games with duplicates: {len(bad)} of {len(per_game)}", ""]
    L += [f"- {n}: {dd} duplicates in {x} exits" for n, x, dd in bad]
    L += ["", f"exits per game: min {min(x for _, x, _ in per_game)}, max {max(x for _, x, _ in per_game)}", ""]
    OUT.write_text("\n".join(L), "utf8")
    print("wrote", OUT, "| pDrawCards classes:", dict(draw_classes), "| games with dup exits:", len(bad))


if __name__ == "__main__":
    main()
