"""Write docs/problem_report.md: the problems of the differential test (the engine against the BGA logs), with the log events of each turn.

    python scripts/problem_report.py [out.md]

It runs `scripts/problem_list.py` (about 6 minutes, all cores) and adds, for every problem, the events of the turn as the viewer words them. Notes on what is known about a problem are
kept in `data_manual/problem_notes.json` ({"<table> <turn>": "text"}): edit that file, not the report.
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from ark_nova.parser import parse_log  # noqa: E402
from ark_nova.replay.actions import turn_events  # noqa: E402
from ark_nova.replay.view import render_log  # noqa: E402


def main() -> None:
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "docs" / "problem_report.md"
    tmp = ROOT / "problems.tmp.json"
    subprocess.run([sys.executable, str(ROOT / "scripts" / "problem_list.py"), str(tmp)], check=True, cwd=ROOT, stdout=subprocess.DEVNULL)
    rows = json.loads(tmp.read_text(encoding="utf-8"))
    tmp.unlink()
    notes_path = ROOT / "data_manual" / "problem_notes.json"
    notes = json.loads(notes_path.read_text(encoding="utf-8")) if notes_path.exists() else {}
    illegal = sum(r["kind"] == "illegal" for r in rows)
    lines = ["# Differential problems", "",
             "Generated by `scripts/problem_report.py` from the differential run on `log_examples/` (the engine plays every logged turn from the log's own state and is compared with the log). "
             "The first problem of a game is the one to look at; later ones may follow from it. Notes: `data_manual/problem_notes.json`.", "",
             "## Summary", "", "| # | table | turn | kind | problem |", "|---|---|---|---|---|"]
    for i, r in enumerate(rows, 1):
        lines.append(f"| {i} | {r['table']} | {r['turn']} | {r['kind']} | {r['text'].split(': ', 1)[-1][:160]} |")
    lines += ["", f"{len(rows)} problems in {len({r['table'] for r in rows})} games ({illegal} illegal moves, {len(rows) - illegal} state mismatches).", ""]
    cache: dict = {}
    for r in rows:
        if r["table"] not in cache:
            cache[r["table"]] = turn_events(parse_log(str(ROOT / "log_examples" / f"{r['table']}.json")))
        events = cache[r["table"]][r["turn"]] if 0 <= r["turn"] < len(cache[r["table"]]) else []
        lines += [f"## {r['table']} turn {r['turn']} ({r['kind']})", "", f"**Error:** {r['text'].split(': ', 1)[-1]}", ""]
        note = notes.get(f"{r['table']} {r['turn']}")
        if note:
            lines += [f"**Notes:** {note}", ""]
        lines += ["| order | event | log text |", "|---|---|---|"]
        for e in events:
            if e.type == "gameStateChangePrivateArg":
                continue
            text = render_log(e.log, e.args) if e.log else ""
            lines.append(f"| {e.order} | {e.type} | {text[:150].replace('|', '/')} |")
        lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(rows)} problems written to {out}")


if __name__ == "__main__":
    main()
