"""Static game data (generated by scripts/import_data.py from data_manual/ + the upstream repo)."""
import json
import re
from functools import lru_cache
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent
_BGA_ID = re.compile(r"^([ASPF])(\d+)_([A-Za-z0-9_]+?)(_MW)?$")


@lru_cache(maxsize=None)
def _load(name: str) -> list:
    return json.loads((DATA_DIR / f"{name}.json").read_text("utf8"))


def animals() -> list[dict]:
    return _load("animals")


def sponsors() -> list[dict]:
    return _load("sponsors")


def projects() -> list[dict]:
    return _load("projects")


def endgames() -> list[dict]:
    return _load("endgames")


def maps() -> list[dict]:
    return _load("maps")


@lru_cache(maxsize=None)
def cards_by_key() -> dict[str, dict]:
    """All cards keyed by letter+number (A414, S231, P127, F003)."""
    return {c["key"]: c for f in (animals, sponsors, projects, endgames) for c in f()}


def parse_bga_card_id(bga_id: str) -> tuple[str, bool]:
    """'F001_LargeAnimalZoo_MW' -> ('F001', True): (card key, is Marine Worlds variant)."""
    m = _BGA_ID.match(bga_id)
    if not m:
        raise ValueError(f"not a BGA card id: {bga_id!r}")
    return f"{m.group(1)}{int(m.group(2)):03d}", bool(m.group(4))


def map_by_id(map_id: str) -> dict:
    for m in maps():
        if m["id"] == str(map_id):
            return m
    raise KeyError(map_id)
